#!/usr/bin/env python3
"""Build a Gemini Notebook (NotebookLM) notebook from the GFR Chapter 6 corpus.

Uploads the Markdown knowledge base generated by `node data/_docs.js`, then runs
three grounded chat turns that demonstrate the notebook answers from the sources
rather than from model memory.

Prerequisites
    1.  pip install "notebooklm-py[browser]"
    2.  notebooklm login --master-token --account <you@example.com>
        (one-time browser OAuth; see the notebooklm-py SKILL.md)
    3.  node data/_docs.js          # regenerate docs/ from the data files

Usage
    python3 build_notebook.py                 # create the notebook and upload
    python3 build_notebook.py --title "..."   # custom title
    python3 build_notebook.py --dry-run       # list the sources, upload nothing
    python3 build_notebook.py --demo          # also run the three chat turns

Nothing here reads or writes credentials. The library handles auth from the
profile directory it owns.
"""

import argparse
import glob
import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DELIVERABLE = os.path.abspath(os.path.join(HERE, "..", ".."))
DOCS = os.path.join(DELIVERABLE, "docs")

# One combined file plus the per-rule files gives NotebookLM both a single
# coherent document and fine-grained retrieval.
SOURCES = [
    "gfr-chapter-6-complete.md",
    "index.md",
    "amendments.md",
    "narration-transcript.md",
]
SOURCE_GLOBS = ["rule-*.md"]

DEMO_QUESTIONS = [
    "Rule 155 ke tehat Local Purchase Committee kitne members ka hota hai, "
    "aur kaun level decide karta hai?",
    "10 July 2024 ke amendment ke baad GeM par direct purchase ka threshold kya "
    "hai? Poora ladder batao.",
    "Non-consulting services ke liye agar Rules 198-205 mein koi circumstance "
    "cover na ho, toh kaunse rules apply hote hain?",
]


def collect_sources():
    files = []
    for name in SOURCES:
        p = os.path.join(DOCS, name)
        if os.path.exists(p):
            files.append(p)
        else:
            print("  ! missing %s — run `node data/_docs.js`" % name)
    for pattern in SOURCE_GLOBS:
        files.extend(sorted(glob.glob(os.path.join(DOCS, pattern))))
    if not files:
        sys.exit("no sources found in %s — run `node data/_docs.js` first" % DOCS)
    return files


def nlm(*args, expect_json=True):
    """Run the notebooklm CLI and return parsed stdout."""
    cmd = ["notebooklm"] + list(args) + (["--json"] if expect_json else [])
    p = subprocess.run(cmd, capture_output=True, text=True)
    if p.returncode != 0:
        sys.stderr.write(p.stdout + p.stderr)
        sys.exit("notebooklm %s failed (exit %d)" % (" ".join(args), p.returncode))
    if not expect_json:
        return p.stdout
    try:
        return json.loads(p.stdout)
    except json.JSONDecodeError:
        sys.stderr.write(p.stdout + p.stderr)
        sys.exit("notebooklm %s did not return JSON" % " ".join(args))


def main():
    ap = argparse.ArgumentParser(description="Build a NotebookLM notebook from GFR Chapter 6")
    ap.add_argument("--title", default="GFR 2017 Chapter 6 — Rules 142 to 206")
    ap.add_argument("--dry-run", action="store_true", help="list sources, upload nothing")
    ap.add_argument("--demo", action="store_true", help="run the grounded chat turns")
    args = ap.parse_args()

    sources = collect_sources()
    total = sum(os.path.getsize(f) for f in sources)
    print("sources : %d files, %.1f KB" % (len(sources), total / 1024.0))
    for f in sources:
        print("   %-42s %7d bytes" % (os.path.basename(f), os.path.getsize(f)))
    if args.dry_run:
        return 0

    nb = nlm("notebook", "create", "--title", args.title)
    nb_id = nb.get("notebook", {}).get("id") or nb.get("id")
    if not nb_id:
        sys.exit("could not read the new notebook id from: %s" % json.dumps(nb)[:400])
    print("\nnotebook : %s (%s)" % (nb_id, args.title))

    failed = []
    for f in sources:
        r = nlm("source", "add", "--notebook", nb_id, "--file", f)
        ok = bool(r.get("source") or r.get("id"))
        print("   %-42s %s" % (os.path.basename(f), "ok" if ok else "FAILED"))
        if not ok:
            failed.append(f)
    print("\nuploaded : %d/%d" % (len(sources) - len(failed), len(sources)))
    if failed:
        sys.stderr.write("failed: %s\n" % ", ".join(os.path.basename(f) for f in failed))

    if args.demo:
        print("\n=== grounded chat ===")
        for q in DEMO_QUESTIONS:
            print("\nQ: " + q)
            r = nlm("chat", "--notebook", nb_id, "--message", q)
            ans = (r.get("answer") or r.get("text") or r.get("content") or "").strip()
            print("A: " + (ans[:900] + ("..." if len(ans) > 900 else "")))
            cites = r.get("citations") or r.get("sources") or []
            if cites:
                print("   grounded in: " + ", ".join(str(c) for c in cites[:4]))

    print("\nnotebook id : %s" % nb_id)
    print("open with   : notebooklm notebook open --notebook %s" % nb_id)
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
